# Generated by Django 4.0.5 on 2022-06-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'Residencial'), ('C', 'Comercial'), ('F', 'Fax'), ('E', 'E-mail'), ('M', 'Celular')], max_length=1)),
                ('contato', models.CharField(max_length=256)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pessoa_app.pessoa')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
            },
        ),
    ]
