# Generated by Django 4.0.5 on 2022-06-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoa_app', '0002_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='Pessoa_app.pessoa'),
        ),
    ]
