# Generated by Django 4.0.5 on 2022-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoa_app', '0004_alter_contato_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Fax', 'Fax'), ('E-mail', 'E-mail'), ('Celular', 'Celular')], max_length=11),
        ),
    ]
